name: Deploy
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: bahmutov/npm-install@v1
      - run: npm run lint
  typecheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: bahmutov/npm-install@v1
      - run: npm run typecheck
  vitest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: bahmutov/npm-install@v1
      - run: npm run test
  playwright:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: bahmutov/npm-install@v1
      - run: npm run test:e2e:install
      - run: npm run test:e2e
        env:
          MOCKS: true
          FIXTURES_DIR: ./tests/fixtures
          AZURE_MAPS_CLIENT_ID: 00000000-0000-0000-0000-000000000000
          AZURE_LOG_LEVEL: info
  provision:
    runs-on: ubuntu-22.04
    needs: [lint, typecheck, vitest, playwright]
    permissions:
      id-token: write
    outputs:
      mapsAccountId: ${{ steps.provision.outputs.mapsAccountId }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: bahmutov/npm-install@v1
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: azure/bicep-deploy@v2
        id: provision
        with:
          type: deployment
          operation: create
          scope: resourceGroup
          name: Provision
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
          template-file: ./infra/main.bicep
          masked-outputs: "webClientId,mapsClientId"
      - run: npx tsx scripts/link-to-netlify.ts
        env:
          AZURE_TENANT_ID: ${{ steps.provision.outputs.tenantId }}
          AZURE_WEB_ID: ${{ steps.provision.outputs.webId }}
          AZURE_WEB_CLIENT_ID: ${{ steps.provision.outputs.webClientId }}
          AZURE_MAPS_CLIENT_ID: ${{ steps.provision.outputs.mapsClientId }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_ACCOUNT_ID: ${{ secrets.NETLIFY_ACCOUNT_ID }}
  deploy:
    runs-on: ubuntu-22.04
    needs: [provision]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: bahmutov/npm-install@v1
      - run: npm run build
      - run: npx netlify deploy --prod --no-build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
